### ISSUE TITLE
when configuring the integration, it gives an error 

### ISSUE THREAD

**Issue by motogon** [incaseoftrouble/whatsminer-homeassistant#1]
Hi 
when configuring the integration, it gives an error 

In the logs, I can't find anything related to this problem. 

![изображение](https://github.com/incaseoftrouble/whatsminer-homeassistant/assets/12997195/883f3376-3c56-4e7b-8a9e-99be8d00a094)

please advise, where can I see the cause of this error?
thank

**Comment by motogon** [comment]
ps I fill in the ip and password field correctly.

**Comment by incaseoftrouble** [comment]
This is still very much a WIP project and I currently don't have the time to work on it, sorry! Your best option is to fork this project and fix the error yourself :(

**Comment by An0n1muS1994** [comment]
> ps I fill in the ip and password field correctly.

Have you managed to solve this error ?
